In [147]:
# Gerando Modelo de Machine Learning (Classificação) com Algoritmo Naive Bayes
# Composição de Vendas Compras Centralizadas no Governo Federal

In [148]:
# Autor: Rafael Henrique Ribeiro Amancio
# -*- coding: utf-8 -*-

In [149]:
#Conjunto de importacoes
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.cross_validation import train_test_split

In [150]:
#Carrega o dataset com os dados para o treinamento e validacao
dados_compras_treino = pd.read_csv("201807_CPGFComprasCentralizadasBaseTreinamento.csv", encoding="utf-8")

In [151]:
#Definição dos atributos que deverao ser treinados para gerar o modelo de classificacao
data_treino = np.array(dados_compras_treino[['ANO', 'MESES', 'TRANSACAO', 'EMPRESA', 'TIPO_COMPRA', 'VALOR_TRANSACAO']])
#Definição do atributo de classificacao
data_classif = np.array(dados_compras_treino['CUSTO_COMPRASNUM'])

In [152]:
#Definição dos conjuntos de treinamento e validação
x_treino, x_val, y_treino, y_val = train_test_split(data_treino, data_classif, test_size=0.10)

In [153]:
#Apresentacao dos dados selecionados para o conjunto de treinamento e validacao
print("-----------------------")
print("Conjunto de Treinamento")
print(x_treino)
print("Conjunto de Validacao")
print(x_val)
print("-----------------------")

-----------------------
Conjunto de Treinamento
[[2018    7    1    2    1  601]
 [2018    7    1    2    1 1178]
 [2018    7    1    3    1  283]
 ...
 [2018    7    1    2    1  783]
 [2018    7    1    3    1  747]
 [2018    7    1    2    1 1856]]
Conjunto de Validacao
[[2018    7    1    3    1  342]
 [2018    7    1    2    1  677]
 [2018    7    1    2    1  609]
 [2018    7    1    2    1  600]
 [2018    7    1    2    1 1938]
 [2018    7    1    2    1  222]
 [2018    7    1    2    1  801]
 [2018    7    1    2    1 1353]
 [2018    7    1    2    1 1028]
 [2018    7    1    2    1  648]
 [2018    7    1    2    1  519]
 [2018    7    1    3    1 2031]
 [2018    7    1    2    1  941]
 [2018    7    1    3    1  283]
 [2018    7    1    4    1  476]
 [2018    7    1    2    1  558]
 [2018    7    1    2    1  283]
 [2018    7    1    3    1 1956]
 [2018    7    1    1    1  466]
 [2018    7    1    2    1  329]
 [2018    7    1    2    1  756]
 [2018    7    1    1    1  307]


In [154]:
#Treinamento do modelo com os dados atribuidos ao conjunto de treinamento
modelo_NB = GaussianNB()
modelo_NB.fit(x_treino, y_treino)

GaussianNB(priors=None)

In [155]:
#Predição e acurácia para o conjunto de treinamento
print("Predicao para o conjunto de treinamento")
y_pred_treino = modelo_NB.predict(x_treino)
print("Acuracia para o conjunto de treinamento")
print(accuracy_score(y_treino, y_pred_treino))
print("-----------------------")

Predicao para o conjunto de treinamento
Acuracia para o conjunto de treinamento
0.9723502304147466
-----------------------


In [156]:
#Predição e acurácia para o conjunto de validação
print("Predicao para o conjunto de validacao")
y_pred_val = modelo_NB.predict(x_val)
print("Acuracia para o conjunto de validacao")
print(accuracy_score(y_val, y_pred_val))
print("-----------------------")

Predicao para o conjunto de validacao
Acuracia para o conjunto de validacao
1.0
-----------------------
