In [18]:
# Gerando Modelo de Machine Learning (Classificação) com Algoritmo Naive Bayes
# Composição de Vendas Compras Centralizadas no Governo Federal

In [23]:
# Autor: Rafael Henrique Ribeiro Amancio
# -*- coding: utf-8 -*-

In [24]:
#Conjunto de importacoes
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.cross_validation import train_test_split

In [25]:
#Carrega o dataset com os dados para o treinamento e validacao
dados_compras_treino = pd.read_csv("dados_limitecredito.csv", encoding="utf-8")

In [26]:
#Definição dos atributos que deverao ser treinados para gerar o modelo de classificacao
data_treino = np.array(dados_compras_treino[['historico_credito','divida', 'garantias', 'renda']])
#Definição do atributo de classificacao
data_classif = np.array(dados_compras_treino['Risco'])

In [27]:
#Definição dos conjuntos de treinamento e validação
x_treino, x_val, y_treino, y_val = train_test_split(data_treino, data_classif, test_size=0.10)

In [28]:
#Apresentacao dos dados selecionados para o conjunto de treinamento e validacao
print("-----------------------")
print("Conjunto de Treinamento")
print(x_treino)
print("Conjunto de Validacao")
print(x_val)
print("-----------------------")

-----------------------
Conjunto de Treinamento
[[    1     1     1 12000]
 [    2     1     2 40000]
 [    2     1     1 40000]
 [    1     2     1 10000]
 [    3     2     1  9000]
 [    2     1     1 38900]
 [    3     1     1 56000]
 [    3     2     1 56709]
 [    2     2     1 28000]
 [    3     2     1 20000]
 [    1     1     2 43222]
 [    1     2     1 23780]]
Conjunto de Validacao
[[    2     1     1 29000]
 [    3     2     2 45600]]
-----------------------


In [29]:
#Treinamento do modelo com os dados atribuidos ao conjunto de treinamento
modelo_NB = GaussianNB()
modelo_NB.fit(x_treino, y_treino)

GaussianNB(priors=None)

In [30]:
#Predição e acurácia para o conjunto de treinamento
print("Predicao para o conjunto de treinamento")
y_pred_treino = modelo_NB.predict(x_treino)
print("Acuracia para o conjunto de treinamento")
print(accuracy_score(y_treino, y_pred_treino))
print("-----------------------")

Predicao para o conjunto de treinamento
Acuracia para o conjunto de treinamento
0.8333333333333334
-----------------------


In [31]:
#Predição e acurácia para o conjunto de validação
print("Predicao para o conjunto de validacao")
y_pred_val = modelo_NB.predict(x_val)
print("Acuracia para o conjunto de validacao")
print(accuracy_score(y_val, y_pred_val))
print("-----------------------")

Predicao para o conjunto de validacao
Acuracia para o conjunto de validacao
0.5
-----------------------
